### ISSUE TITLE
Locally built docker image has wine error

### ISSUE THREAD

**Issue by virtuald** [cdrx/docker-pyinstaller#10]
`wine: '/tmp/.wine-0/server-fd04-1601bf9/socket' is not a socket`

It seems that I have to run wineserver first, then it will work. any idea why? Doesn't seem to be the case on the one distributed on docker hub.

**Comment by cdrx** [comment]
I've just rebuilt the py3 on Windows image and can't reproduce that error. Possibly another selinux issue?

**Comment by cdrx** [comment]
Are you bind mounting /tmp/ into the container?
