### ISSUE TITLE
Can you compile several spec files at once?

### ISSUE THREAD

**Issue by cpainchaud** [cdrx/docker-pyinstaller#110]
I have a folder with several .spec files but only first one is built! others are ignored!

**Comment by TheTechRobo** [comment]
In theory you could make multiple Actions.

**Comment by cpainchaud** [comment]
Hi, yes it's what I am doing but it's adding some sort of overhead as it's spawning the environment several times and I have to edit the action yaml file to add a paragraph for each of them.
I am probably going to write a an 'action file' generator which will be updated by another action ....
