### ISSUE TITLE
0194:err:mscoree:LoadLibraryShim error reading registry key for installroot

### ISSUE THREAD

**Issue by baaaaaaaaaaaaam** [cdrx/docker-pyinstaller#117]
when start   wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python37;   

then occured below message !!!

![image](https://user-images.githubusercontent.com/57000871/177264338-8e36b172-7e54-444b-98ce-f7db28549b08.png)

why?

**Comment by cdrx** [comment]
No idea. Not a bug in this project. Check with the Wine project.
