### ISSUE TITLE
Exe outputs: "Z:\src\.gitignore could not be extracted!"

### ISSUE THREAD

**Issue by their** [cdrx/docker-pyinstaller#14]
When running the compiled exe in a Windows command prompt, the output is:

```Z:\src\.gitignore could not be extracted!```

The command used to build is:

```~/Trumpocalypse/UI$ docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows:python2 "pyinstaller --onefile Trumpocalypse.py".```

Where ```Trumpocalypse.py``` resides in the folder ```~/Trumpocalypse/UI/```.

There is no requirements file used. Could this be an issue? Requirements are: pygame 1.9.1 and python 2.7.

**Comment by cdrx** [comment]
I dont think this is a bug in `docker-pyinstaller` as that message comes from `PyInstaller` itself -- best to file this on their issue tracker.
