### ISSUE TITLE
Error loading Python DLL python35.dll

### ISSUE THREAD

**Issue by Kenterfie** [cdrx/docker-pyinstaller#15]
I get following error on Windows

`Error loading Python DLL: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI19602\python35.dll (error code 998)`

I have seen something similar at git pyinstaller project, but no progress since months. Any ideas to fix the problem?

**Comment by ManuelLR** [comment]
Same Issue in Windows 7 Professional N (x64) compile from docker running in ArchLinux.
The same executable in Windows 10 work.

**Comment by mat128** [comment]
Same here. Works on Windows 10. No error code.

**Comment by jameshilliard** [comment]
This is likely due to Visual C++ Redistributable being missing, [this](https://github.com/cdrx/docker-pyinstaller/pull/18) should work on windows 7.

**Comment by cdrx** [comment]
@Kenterfie @ManuelLR  this should be fixed now, could you please reopen the issue if you still see this error?
