### ISSUE TITLE
Changing Python to version 3.6.3 fails to build

### ISSUE THREAD

**Issue by Viatrak** [cdrx/docker-pyinstaller#17]

**Comment by Viatrak** [comment]
I realize that this isn't supported. Are there any plans to add support for this version?

**Comment by cdrx** [comment]
I need to add it reasonably soon, want to use f-strings.

Where does it not work, Windows or Linux?

**Comment by Viatrak** [comment]
My failed build attempt was on the windows version.

**Comment by mat128** [comment]
I'm getting this on a py36 windows build:
```
 ---> Running in c8d5e5080096
wine: cannot find 'C:\Python36\Scripts\pip.exe'
```

Still investigating atm

**Comment by jameshilliard** [comment]
I got python 3.6 working on windows [here](https://github.com/cdrx/docker-pyinstaller/pull/18).

**Comment by cdrx** [comment]
@mat128 @Viatrak the version on Docker Hub now has Python 3.6 on Windows, thanks to @jameshilliard
