### ISSUE TITLE
Getting "Microsoft Visual C++ 14.0 is required " error when cythonize

### ISSUE THREAD

**Issue by vkahawala** [cdrx/docker-pyinstaller#22]
Hi @cdrx 

I used the windows 64 pyinstaller-windows image with a simple app which uses tkinter and it works perfectly. Then I tried to use the image with an application with cython extension. Then I got below error.

_error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools_

What might be the reason?

Thanks and Regards,
Venura

**Comment by themanifold** [comment]
I had a look round and came across this post: https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

What I did to fix my problem was just to force upgrade the version of setuptools: `pip install --upgrade setuptools` after execing into the container. The official win64 docker images haven't been built for a while, so you'll need to edit the Dockerfile and force change the version there, or just base an image off the official image with the command I suggest as a step.

**Comment by themanifold** [comment]
OK, so for me, I was having the same error installing the typed-ast module as it needs to be compiled. So the two steps I needed to do are:

1. `pip install --upgrade setuptools` - this needs to be done before your `pip install -r requirements.txt` step
2. Download and `ADD` in your dockerfile the correct, pre-compiled, typed-ast module from https://www.lfd.uci.edu/~gohlke/pythonlibs/
   - You must install `wheel` first with pip
   - then it would be `pip install typed_ast‑1.1.0‑cp36‑cp36m‑win_amd64.whl`
