### ISSUE TITLE
Build process broken with Ubuntu 16.04 as a base

### ISSUE THREAD

**Issue by runeimp** [cdrx/docker-pyinstaller#25]
Ubuntu 16.04 is no longer viable as a base for these images. The `apt-get` command will install nothing as the package servers for that version of Ubuntu seems to be gone now.

I was able to fix this locally for Linux/Python 3 replacing `FROM ubuntu:16.04` with `FROM python:3.6-stretch` and removing `python3` and `libmysqlclient-dev` from the `apt-get` call in the Dockerfile. This produced an image that was 935MB and produced binaries that worked fine on Ubuntu 17.10.

I also tried the same setup but with `FROM python:3.6-slim-stretch` that created a Docker image that was 491MB. It's binaries also worked on Ubuntu 17.10.

Then I tried `FROM python:3.6-alpine` and replacing the original `apt-get` calls with `apk add --update-cache python3-dev git`. This left me with a Docker image that was 199MB and was able to produce binaries that worked on Ubuntu 17.10 as well.

For the Windows 64-bit/Python 3 Dockerfile I could not find success until I used `FROM ubuntu:17.10` and added ` gpg-agent`, and `rename` to the `apt-get` call. This produced a Docker image that was 1.15GB. I didn't get around to testing other bases for the image.

None of these have been extensively tested. So I didn't create a Pull Request. I hope this issue and info helps.  😃

**Comment by cdrx** [comment]
Thanks for the research -- rebasing on Alpine is a possibility in the future because of the tiny image sizes for sure.

Ubuntu 16.04 is supported into 2021 so I'm curious why it wouldn't build for you using that base image. Did it throw up an error or something?

**Comment by runeimp** [comment]
No errors beyond it can't find packages. Just updated a local system for the same reason. Essentially no packages found. Isn't 16.10 the LTS version though? They've officially dropped support for 16.04 to my knowledge.

**Comment by runeimp** [comment]
OK, looks like the package servers may have just been returning empty responses for a few days. Everything is working fine on Ubuntu 16.04.4 LTS again.
