### ISSUE TITLE
Pre-install git to wine (feature request)

### ISSUE THREAD

**Issue by deeuu** [cdrx/docker-pyinstaller#28]
Hi,

Thanks for these really useful containers.

Would it be possible to install git into wine to support the installation of git repos via `pip install`?
E.g. using the windows container, I'm getting the following error
`Error [WinError 2] File not found while executing command git clone -q ssh://git@...`

Thanks

**Comment by white-gecko** [comment]
Maybe this also works without forking the docker file using this command:

```
docker run -it -v "$(pwd):/src/" --entrypoint /bin/sh cdrx/pyinstaller-windows:python3 -c \
"apt-get update -y && \
 apt-get install -y git && \
 git clone https://custom-package /wine/drive_c/package-name && \
 pip install -e /wine/drive_c/package-name && \
 /entrypoint.sh"
```
