### ISSUE TITLE
Creation of .spec file

### ISSUE THREAD

**Issue by michyArya** [cdrx/docker-pyinstaller#29]
Hi,
I wanted to create an .exe for a python application. I followed the instruction to create a .spec file first, so I ran `docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows pyinstaller <script_name>.py` as suggested in the README, but I got the following output:

```
pyinstaller <script_name>.py
usage: pyinstaller [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                   [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                   [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d] [-s] [--noupx] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--distpath DIR]
                   [--workpath WORKPATH] [-y] [--upx-dir UPX_DIR] [-a]
                   [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
pyinstaller: error: the following arguments are required: scriptname

```
I then got inside the container and ran `pyinstaller --onefile <script_name>.py`. 
Then, once the .spec file was generated, I ran `docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows` to create the exe. When I then launch the executable, something seems to be missing.
I have also tried to run the installer withouth the `--onefile` option but I still get an executable which breaks.

Would you have any suggestions, especially around the creation of the .spec file? As running it in a container shouldn't give any error, as everything that is needed is there.

Thank you,
MIchela

**Comment by hmarlo** [comment]
Which is the error you get after the .spec file is generated. Can you provide the version that you are using inside and outside the docker container?

**Comment by jahaugum** [comment]
Put quotes around the pyinstaller command and it's arguments: `docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows "pyinstaller <script_name>.py"`
