### ISSUE TITLE
Running Parameters to Docker Images

### ISSUE THREAD

**Issue by bmustiata** [cdrx/docker-pyinstaller#3]
The docker images should be usable standalone, without requiring the installation of an initial `pyinstaller` for the initial creation of the `*.spec` files.

**Comment by cdrx** [comment]
Do you think if no spec file is present, we should generate one with PyInstaller and rerun the build?

**Comment by bmustiata** [comment]
It would make sense I guess. The only problem is that you need to specify the `main.py` program for `pyinstaller` to start processing. And this is already possible, with the current entrypoint script:

```sh
docker run -it --rm `pwd`:/src cdrx/pyinstaller-windows:python2 pyinstaller /src/main.py
```

The thing that annoyed me was that I needed to have `pyinstaller` already installed, only to create the spec file, even if from that moment onward I would use only the docker container.

**Comment by cdrx** [comment]
Makes sense

I've added a note to the README about how to generate a spec file if one isn't present, but some knowledge of PyInstaller is required before using this :)

**Comment by Hacker-x751** [comment]
how about src
and how to change directory to src
