### ISSUE TITLE
Built binaries won't run on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kasokz** [cdrx/docker-pyinstaller#35]
The main reason I used this docker image was to build PyInstaller binaries for a Ubuntu 16.04 on my Ubuntu 18.04. That worked good until the last change, since the base image was Ubuntu 16.04 so the binary was built on the same platform as my target platform.

With the current image, building the project and trying to run on an Ubuntu 16.04 system following error occurs:

> [27488] Error loading Python lib '/etc/job2/temp/_MEIgCEd5f/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /etc/job2/temp/_MEIgCEd5f/libpython3.6m.so.1.0)

I used the python3 Linux image.

I propose adding more tags for different Linux distros so that you can choose on which platform you want to build. I have currently solved my problem by modifiying the Dockerfile locally to use the Ubuntu 16.04 base again.

**Comment by itouch5000** [comment]
I had the same issue. [This pull request](https://github.com/cdrx/docker-pyinstaller/pull/37) should solve your problem.
