### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'noarchive'

### ISSUE THREAD

**Issue by Shivam23Thaman** [cdrx/docker-pyinstaller#36]
I have installed the docker correctly but have got this error. 
![screenshot from 2018-10-23 17-12-43](https://user-images.githubusercontent.com/21020234/47358265-e9e94080-d6e6-11e8-8a04-059b2d2b2cc4.png)

**Comment by jdeltoft** [comment]
Yea, I'm getting this same failure.
