### ISSUE TITLE
Linux image for Python3 not running on GitLab CI Runner

### ISSUE THREAD

**Issue by b2m** [cdrx/docker-pyinstaller#38]
**Enviroment**

GitLab CI Runner in [Docker mode with bash shell](https://docs.gitlab.com/runner/shells/) and current [cdrx/pyinstaller-linux:python3](https://hub.docker.com/r/cdrx/pyinstaller-linux) image.

**Problem description:**

Some CI servers like the current GitLab CI Runners will execute scripts in docker containers in a **non**-interactive way. In this mode the `.bashrc` will not get executed which is discussed in detail in [this StackExchange thread](https://unix.stackexchange.com/questions/257571/why-does-bashrc-check-whether-the-current-shell-is-interactive). Therefore the changes added to the `.bashrc` in the current Dockerfile for the linux python3 image are ignored. This results in errors like: _"pip command not found"_, because obviously the [changes to `$PATH`](https://github.com/cdrx/docker-pyinstaller/blob/e16b9a9c49934d998a969839566f11b7c69405c5/linux/py3/Dockerfile#L29) are ignored...

**Problem delimitation:**

I did not explicitly check how other CI solutions currently behave regarding interactive/non-interactive shell code execution.

**Comment by GabLeRoux** [comment]
Hey there, I didn't try with custom `requirements.txt` yet, but here's how I managed to get gitlab-ci working:

https://gitlab.com/gableroux/python-windows-application-example

:v:

**Comment by b2m** [comment]
I really like the idea of using docker in docker to avoid the problems caused by the way the GitLab Runner "pipes" the script commands to the image.

Unfortunately this also means that the docker image for PyInstaller won't get cached and needs to be downloaded with every build. This unnecessarily increases network traffic and build time. This could be mitigated by using caching... but in my opinion this is more than should be necessary.

I guess you noticed the `sh: 1: set: Illegal option -o pipefail` error message in your first try?

As far as I investigated this problem the reason for this is, that GitLab CI will run some commands before piping the user provided `script` part(s). These commands then will get executed via `sh -c "$@"` in the [`entrypoint.sh`](https://github.com/cdrx/docker-pyinstaller/blob/e16b9a9c49934d998a969839566f11b7c69405c5/linux/py3/entrypoint.sh#L36). And `sh` defaults to a "lesser" shell, which then fails on the bash commands.

Again you can circumvent this by [overwriting the entrypoint for the docker image in the GitLab CI configuration file](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image) and provide you own script... but it would be more comfortable for users to adapt the `entrypoint.sh` to use `bash` instead of `sh` to execute the user provided commands.

**Comment by Skinner927** [comment]
I wanted to share my workaround for this issue (I haven't run this in GitLab CI but I belive the issues are similar).

```
docker run -v "$(pwd):/src/" -v pyenv:/root/.pyenv -ti --rm --entrypoint /bin/bash cdrx/pyinstaller-linux -c '\
  export PS1="$$" && \
  source ~/.bashrc && \
  PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install -s 3.6.7 && \
  pyenv rehash && \
  pyenv shell 3.6.7 && \
  python --version && \
  pip install --upgrade pip && \
  pip install -r requirements.txt && \
  pyinstaller --clean -y --dist ./dist/linux --workpath /tmp package.spec'
```

Some notable things are happening:

1. `-v pyenv:/root/.pyenv` creates a docker volume to store the pyenv environment so Python does not have to be installed every time the container runs. You may want to change the volume name (`pyenv` before the `:`) to the actual name of your project (eg. `-v foobar-pyenv:/root/.pyenv`).

2. `export PS1="$$"` basically gives us a shell prompt which will then allow `source ~/.bashrc` to run properly. The first line of `.bashrc` checks that `$PS1` is non-empty.
