### ISSUE TITLE
Deprecated Ubuntu 12.04 LTS used for Linux Images.

### ISSUE THREAD

**Issue by gabrielcalderon** [cdrx/docker-pyinstaller#39]
Ubuntu 12.04 LTS reached its regular End of Life on April 28, 2017. Please update to Latest Ubuntu or Debian Base. 

[http://releases.ubuntu.com/12.04/](url)

**Comment by s0undt3ch** [comment]
I believe the reason for an older Ubuntu and why it might be kept is to use an old enough Glibc, but I could be wrong.

**Comment by Skinner927** [comment]
It's an old version to increase compatibility range I would believe:
https://pyinstaller.readthedocs.io/en/stable/usage.html#making-linux-apps-forward-compatible
