### ISSUE TITLE
Lower GLIBC version

### ISSUE THREAD

**Issue by s0undt3ch** [cdrx/docker-pyinstaller#44]
The current version of ubuntu used for the pyinstaller py3 image is not old enough to create binaries that run under CentOS 6.

Can we switch the base image to CentOS 6 instead of ubuntu 12.04?

**Comment by cdrx** [comment]
The earliest tagged cents 6 release on docker hub is 6.6 which is newer than 12.04, so don't think that would help

Plus it breaks users existing workflows that depend on being able to `apt-get install $dependencies`

**Comment by s0undt3ch** [comment]
CentOS 6 **does** have an earlier GLIBC
```
❯ docker run --rm -it  centos:6  bash
[root@54a1bbe9e1cb /]# ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
```
❯ docker run --rm -it ubuntu:12.04 bash
root@c71533c5ad47:/# ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.18) 2.15
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
```
❯ docker run --rm -it ubuntu:14.04 bash
root@6315a55e0755:/# ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.14) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Could we provide some kind of alternate tagging?

**Comment by s0undt3ch** [comment]
Use 10.04 ?!
```
❯ docker run --rm -it ubuntu:10.04 bash
root@9b17076d76d5:/# ldd --version
ldd (Ubuntu EGLIBC 2.11.1-0ubuntu7) 2.11.1
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by s0undt3ch** [comment]
Hmm, 10,04 doesn't even have recent enough certificates for curl not to complain...

**Comment by makkus** [comment]
I've used the 'debian:7' image with good success. Still, glibc 2.13, so doesn't help for RedHat 6. Also tried a Debian version 6, but that also has certificate expiry issues. Could probably be solved, but at that stage it'd be easier to just create a separate RedHat 6 image...

For reference, here's a list of Distributions and their glibc versions: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Linux_compatibility_matrix

**Comment by s0undt3ch** [comment]
Just for reference, Ubuntu 10.04 is a no go because even if we provide recent enough certificates, its OpenSSL doesn't comply with the latest TLS requirements.
We could provide the certificates instead of downloading them on the image.
It was just too much of a hassle.
I ended up forking and switching to CentOS.
Not going to publicise because we ended up going another route, so we won't maintain those images.

**Comment by makkus** [comment]
Hey @s0undt3ch ,I'm about to switch to CentOS too, would be cool to have your Dockerfile as reference to save me figure out the dependencies I'll need. Would you mind sharing?

**Comment by s0undt3ch** [comment]
https://github.com/s0undt3ch/docker-pyinstaller/commits/hotfix/lower-glic
Can't remember if I have additional changes locally. If I do, I'll push them.

**Comment by makkus** [comment]
Thanks, much appreciated!

**Comment by cdrx** [comment]
I'm not planning to swap the base image to CentOS or lower the Ubuntu version used, so will close this issue. If you need a different version of glibc then please use s0oundt3ch's repo listed above.

**Comment by arossert** [comment]
@s0undt3ch Is your fork still working? seems like the CenOS 6 repo is gone

**Comment by s0undt3ch** [comment]
This hasn't been used in ages...
