### ISSUE TITLE
Unable to get dependencies directly from GitHub

### ISSUE THREAD

**Issue by SkillsLabFR** [cdrx/docker-pyinstaller#47]
My requirement.txt file contains direct links to dependencies:

`https://github.com/ralph-group/pymeasure`
`numpy==1.16.2`
`...`

At the launch of the docker-pyinstaller-windows container I get an error that the archive format is not recognized.

I also tried with the GIt format :
`-e git+https://github.com/ralph-group/pymeasure.git#egg=pymeasure`
but I get another error that says the git command is not recognized.
Can you advise me if there is a solution to use dependencies from GitHub? Thank you in advance!

 Gor

**Comment by white-gecko** [comment]
I think this issue is related and also provides a workaround: https://github.com/cdrx/docker-pyinstaller/issues/28
