### ISSUE TITLE
Multiprocessing not working after compiling

### ISSUE THREAD

**Issue by odelucca** [cdrx/docker-pyinstaller#55]
I am working on a project where I need to do a pretty long number of web requests an wait for their answers. In order to achieve that I am using the `multiprocessing` lib:
```
import multiprocessing

...
print('===> Running multiprocess...')
with multiprocessing.Pool(multiprocessing.cpu_count()) as p:
        similar_result = p.map(func, list)
```

When I try to run the script on Python it works perfectly. But when I compile it to an EXE using your Docker it throws me this error:
```
===> Running multiprocess...
02ca:fixme:reg:GetMaximumProcessorCount semi-stub, returning 8
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ca:fixme:ntdll:server_get_file_info Unsupported info class e
02ef:fixme:ntdll:server_get_file_info Unsupported info class e
02f1:fixme:ntdll:server_get_file_info Unsupported info class e
02f3:fixme:ntdll:server_get_file_info Unsupported info class e
02f5:fixme:ntdll:server_get_file_info Unsupported info class e
02f7:fixme:ntdll:server_get_file_info Unsupported info class e
02f9:fixme:ntdll:server_get_file_info Unsupported info class e
02fb:fixme:ntdll:server_get_file_info Unsupported info class e
```

I've already inserted the `multiprocessing.freeze_support()` as [this recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) suggests:
```
if __name__ == '__main__':
    multiprocessing.freeze_support() # Added to multiprocessing works in Pyinstaller
    run()
```

But it is still not working. 
I think it is something related to the fact that your Docker container uses Wine to compile it. Can you help me?

**Comment by runeimp** [comment]
@odelucca Just to help enlighten the situation; are you on Linux or macOS trying to build an executable for Windows? Is this for the 32-bit or 64-bit Windows PyInstaller container? Also is this for Python 2 or 3? And yes, that does look like a Wine issue.

**Comment by odelucca** [comment]
> @odelucca Just to help enlighten the situation; are you on Linux or macOS trying to build an executable for Windows? Is this for the 32-bit or 64-bit Windows PyInstaller container? Also is this for Python 2 or 3? And yes, that does look like a Wine issue.

I'm on a Linux, Python 3 and trying to compile it using the following Docker run command:
```
$ docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows
```
I think the default is 64-bit on this container, right?

Also, if I remove the multiprocessing it works without any error.

**Comment by runeimp** [comment]
I'm seeing several Python issue at https://bugs.winehq.org/buglist.cgi?quicksearch=python so it could be related to one of those or something entirely new. I tried https://bugs.winehq.org/buglist.cgi?quicksearch=python%20multiprocessing and https://bugs.winehq.org/buglist.cgi?quicksearch=multiprocessing but found nothing. 😞

**Comment by odelucca** [comment]
Can you open a new issue there please? Or should I do that?
