### ISSUE TITLE
Fatal Python error: Py_Initialize: can't initialize sys standard streams

### ISSUE THREAD

**Issue by vigri** [cdrx/docker-pyinstaller#66]
Hello,

I'm trying to use this container to build a windows application inside a jenkins pipeline.

However, I'm getting an error while execution:

```
+ pyinstaller start.spec
0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle
Current thread 0x0000002f (most recent call first):
```
sometimes the outpus is only
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle
Current thread 0x0000002b (most recent call first):
```
This is my pipeline stage:
```
stage('Deliver') {
  agent {
    docker {
      image 'cdrx/pyinstaller-windows:python3'
      args '--entrypoint="" -u root:root -v ${PWD}:/src -w /src'
    }
  }
  steps {
    sh 'pyinstaller start.spec'
  }
}
```

Using wine directly from within the pipeline results in a similar error:
```
+ wine /wine/drive_c/Python36/Scripts/pyinstaller.exe start.spec
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle
Current thread 0x0000002c (most recent call first):
```

Could you tell me please if this is a bug or is there someting I'm missing?

Thanks and best regards

**Comment by gmywq392** [comment]
update for solution...

**Comment by cdrx** [comment]
This is going to be a bug in wine or python so not going to be fixed here; best taken upstream

**Comment by pperevoznyk** [comment]
> Hello,
> 
> I'm trying to use this container to build a windows application inside a jenkins pipeline.
> 
> However, I'm getting an error while execution:
> 
> ```
> + pyinstaller start.spec
> 0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> 0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
> 0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
> 0027:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
> Fatal Python error: Py_Initialize: can't initialize sys standard streams
> OSError: [WinError 6] Invalid handle
> Current thread 0x0000002f (most recent call first):
> ```
> 
> sometimes the outpus is only
> 
> ```
> Fatal Python error: Py_Initialize: can't initialize sys standard streams
> OSError: [WinError 6] Invalid handle
> Current thread 0x0000002b (most recent call first):
> ```
> 
> This is my pipeline stage:
> 
> ```
> stage('Deliver') {
>   agent {
>     docker {
>       image 'cdrx/pyinstaller-windows:python3'
>       args '--entrypoint="" -u root:root -v ${PWD}:/src -w /src'
>     }
>   }
>   steps {
>     sh 'pyinstaller start.spec'
>   }
> }
> ```
> 
> Using wine directly from within the pipeline results in a similar error:
> 
> ```
> + wine /wine/drive_c/Python36/Scripts/pyinstaller.exe start.spec
> Fatal Python error: Py_Initialize: can't initialize sys standard streams
> OSError: [WinError 6] Invalid handle
> Current thread 0x0000002c (most recent call first):
> ```
> 
> Could you tell me please if this is a bug or is there someting I'm missing?
> 
> Thanks and best regards

Hi @vigri, did you achieve any success on this? Facing same issue :(

P.S. Sorry for continuing in closed issue, don't know how to contact reporter directly.

**Comment by vigri** [comment]
> Hi @vigri, did you achieve any success on this? Facing same issue :(
> 
> P.S. Sorry for continuing in closed issue, don't know how to contact reporter directly.


Hi @pperevoznyk,

unfortunately not. I've tested it a couple of days ago again and got random errors.
My current workaround is using a dedicated vm as a jenkins slave with windows and pyinstaller

**Comment by pperevoznyk** [comment]
> > Hi @vigri, did you achieve any success on this? Facing same issue :(
> > P.S. Sorry for continuing in closed issue, don't know how to contact reporter directly.
> 
> Hi @pperevoznyk,
> 
> unfortunately not. I've tested it a couple of days ago again and got random errors.
> My current workaround is using a dedicated vm as a jenkins slave with windows and pyinstaller

Hi @vigri, i see, thanks for the reply.

i'm trying a bit different approach as a workaround.
Im calling the container not by using docker{} pipeline directive, but using direct shell commands from pipeline, like:
sh 'docker container run...', 
still testing the approach, so far it looks better than docker {}

**Comment by bheemann** [comment]
Has anyone here already achieved something new?

**Comment by chucklay** [comment]
Also having this issue in a Jenkins pipeline. Has anyone been able to successfully get this working via Jenkins?

**Comment by yonatankahana** [comment]
@bheemann @chucklay @vigri  @pperevoznyk
i have managed to solve it using `script`.
let's say i have `python setup.py install` that failing or whatever, it will work perfect with:

```bash
script -qefc "python setup.py install" /dev/null
```

it solves my problem with `pyinstaller` too.
