### ISSUE TITLE
How to use UPX for EXE compression?

### ISSUE THREAD

**Issue by shijianjian** [cdrx/docker-pyinstaller#70]
Hi,

Thanks for this work, it is pretty handy for Linux users. While the problem for me is that the EXE can be pretty large for a simple application, which takes 120 MB for a simple page.

I have noticed when running pyinstaller, a message shows that the UPX is currently not avaliable.

```
264 INFO: PyInstaller: 3.5
264 INFO: Python: 3.6.4
269 INFO: Platform: Windows-XP-5.1.2600
279 INFO: UPX is not available.
```

I am wondering is it possible to install it manually, or even to incorporate the UPX into the docker image.

Best,
Jian

**Comment by danielguardicore** [comment]
You can add upx manually by adding it as a command when running the docker container
` -c "apt-get update -y && apt-get install upx -y && /entrypoint.sh"`

**Comment by shijianjian** [comment]
@danielguardicore Do you mean that we can add a Linux package to a Windows Docker Image if we are running docker on a Linux machine?

**Comment by danielguardicore** [comment]
Oh, my bad. I missed that it's for windows.
For windows, you can manually download UPX as a zip, unzip it 
https://github.com/upx/upx/releases/download/v3.94/upx394w.zip

You then make sure the binary is in the executable path and pyinstaller will automatically use it.
