### ISSUE TITLE
Parallel builds collide in resulting file

### ISSUE THREAD

**Issue by danielguardicore** [cdrx/docker-pyinstaller#81]
If we run two containers at the same time from the same source dir, they will overwrite the resulting file. 
Entrypoint.sh should distinguish and output to python3/linux/whatever and python2/linux/whatever, and as appropriate to the other OSes/versions

This can happen if we run python3 and python2 at the same time

**Comment by danielguardicore** [comment]
@cdrx any wish on how to fix this or can I make up my own solution and PR it?

**Comment by cdrx** [comment]
I'm open to ideas but not sure how this could be fixed without breaking existing installations by changing the path

**Comment by danielguardicore** [comment]
Not sure how many scripts you have that rely on it 😅 
But I thought of just renaming the resulting file and creating a symlink to it in the original path.

**Comment by acepace** [comment]
Meh, won't implement it (different user, same person). Feel free to close
