### ISSUE TITLE
openSSL wget url changed

### ISSUE THREAD

**Issue by peter-lih** [cdrx/docker-pyinstaller#87]
In Dockerfile-py3-amd64 "openssl-1.0.2u" should use "openssl-1.1.1f". As provide from
 https://www.openssl.org/source/ . Thanks!

**Comment by acepace** [comment]
Yeah, that's not a good idea. Old Ubuntu doesn't support that version of openssl and we want to keep using the old distribution.

**Comment by cdrx** [comment]
Agreed
