### ISSUE TITLE
Add git to Wine server

### ISSUE THREAD

**Issue by malwaredllc** [cdrx/docker-pyinstaller#91]
Do you happen to know if adding git to the Wine server is possible? My requirements.txt file contains a reference to git which is causing it to fail when compiling an executable for Windows, as the Wine server does not have git installed.

**Example in requirements.txt**
`git+https://github.com/jtgrassie/pyrx.git#egg=pyrx`

**Comment by jameshilliard** [comment]
@malwaredllc Well you don't actually need git to point your requirements.txt to github, just point it to the archive file download location, for example https://github.com/jtgrassie/pyrx/archive/c5c87ed0c3252d2ffdd1be805129b83697378379.tar.gz.

Note: If the project is not pure python and has c extensions you will need to precompile the binary wheel on windows, you can then upload the precompiled wheel to github releases and point your requirements.txt to the wheel download link. For example with twisted I use this wheel in my requirements.txt which I precompiled and uploaded to releases https://github.com/jameshilliard/twisted/releases/download/twisted-17.9.0/Twisted-17.9.0-cp36-cp36m-win_amd64.whl.

**Comment by cdrx** [comment]
Closing in favour of #80
