### ISSUE TITLE
Building a one-file executable

### ISSUE THREAD

**Issue by max-tet** [cdrx/docker-pyinstaller#98]
Hi,

I am trying to build a one-file executable. When using pyinstaller directly, I would add the `--onefile` option. But I have found no option to do this with docker-pyinstaller. Is this not supported?

**Comment by jean-emmanuel** [comment]
When generating the .spec file (https://github.com/cdrx/docker-pyinstaller#how-do-i-generate-a-spec-file) you can append `--onefile` to the command.

**Comment by max-tet** [comment]
That worked great, thanks!
